# .github/workflows/ci.yml
name: CI for Server

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  checks: write # Needed for publishing test results

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: install ambrosia
        run: curl -fsSL https://raw.githubusercontent.com/btcgdl/Ambrosia-POS/master/scripts/ambrosia.sh | bash

      - name: Check Ambrosia POS installation
        run: command -v ambrosia

      - name: install phoenixd
        run: curl -fsSL https://raw.githubusercontent.com/btcgdl/Ambrosia-POS/master/scripts/phoenixd.sh | bash

      - name: Check phoenixd installation
        run: command -v phoenixd

      - name: Run phoenixd
        run: phoenixd --chain=testnet --seed=${{ env.CISEED }} &

      - name: Make Gradle wrapper executable
        run: chmod +x ./server/gradlew

      - name: Run tests with Gradle
        working-directory: server
        run: ./gradlew test